Add initial fhir-to-text and nlp route documentation
LinuxForHealth/docs pull request #57
Opened 2021-01-11 18:48 UTC by srcarrier

Looking to get the *.rst content reviewed prior to generating and re-generating all the html content.

2021-01-15 18:28 UTC, ccorley commented on source/routes/fhir-to-text.rst
> +This route need not be invoked by another. Simply enable the route, configure your desired nlp service and FHIR resources will be consumed from Kafka, unstructured data within will be extracted and s
Slight wordsmithing here: "...from Kafka, then unstructured data within..."

2021-01-15 18:29 UTC, ccorley commented on source/routes/nlp.rst
> ++-------------------------+---------------------------------------------------------------------+
Same comment about route name and route URI.

2021-01-15 18:30 UTC, ccorley requested changes
Looks good, just a few minor comments.

2021-01-22 20:07 UTC, srcarrier commented on source/routes/fhir-to-text.rst
> ++-------------------------+-----------------------------------------------------------------------------------+
I noticed some inaccuracies w/ the store and notify route doc:
https://linuxforhealth.github.io/docs/routes/direct-storeandnotify.html#details

The route name in the docs is `direct:storeAndNotify`, whereas the route id is `store-and-notify`

I can push a commit to address that ☝️ as part of this pr, if that makes sense.
I included both the route id and uris in my route doc.

2021-01-25 16:51 UTC, dixonwhitmire reviewed
Hi @srcarrier lgtm 
I did have a question regarding the basic auth parameters. I just wanted to confirm that they are working correctly with external NLP services since we have had to make adjustments for external FHIR servers.
Thanks!

2021-01-25 16:51 UTC, dixonwhitmire commented on source/routes/nlp.rst
> +lfh.connect.nlp.auth=&authMethod=Basic&authUsername=apikey&authPassword=ENC(<YOUR_ENCRYPTED_PASSWORD_HERE>)
Are we able to utilize basic auth for the NLP route using the camel http4 component params?

2021-01-25 21:03 UTC, ccorley commented on source/routes/fhir-to-text.rst
> ++-------------------------+-----------------------------------------------------------------------------------+
That would be great, thanks!

2021-01-25 21:27 UTC, ccorley approved these changes
Looks good.  Thanks for the store & notify fix!

2021-01-26 01:34 UTC, merged